language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

jobs:
  include:
    - stage: Sonar check and code coverage reporting
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: "valfirst-github"
          token:
            secure: "oj5bVWt7nvIGbKxlRcXiqp8xET1QR2NTYKfCCFAJi8WLg2TO/teO7VxG3rregEUnc/1DLfINPs69HAL13wcwH3TcvHeTJ3m6IC7VevJoj+/JK8yKJAyxkBLIE+j2cF+4HVHk72DSGGE+73b8+x1ItFJ/Gr/ISHL8i5dlyDHCcO4="
      script:
        - mvn test jacoco:report coveralls:report
        - if [[ -n "${TRAVIS_PULL_REQUEST_SLUG}" && "${TRAVIS_PULL_REQUEST_SLUG}" != "${TRAVIS_REPO_SLUG}" ]]; then
            echo "The pull request from ${TRAVIS_PULL_REQUEST_SLUG} is an EXTERNAL pull request. Skip sonar analysis and Codacy coverage reporting.";
          else
            mvn sonar:sonar -Dsonar.projectKey=com.github.valfirst:jbehave-junit-runner com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=${CODACY_PROJECT_TOKEN} -DapiToken=${CODACY_API_TOKEN} -Dcommit=${TRAVIS_COMMIT};
          fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
